eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/

server:
  port: 8805
  servlet:
    context-path: /consumer

spring:
  application:
    name: ribbon-consumer
  jms:
    #MQ订阅模式需要设置
    pub-sub-domain: false
  activemq:
      broker-url: tcp://localhost:61616
      #true 表示使用内置的MQ，false则连接服务器
      in-memory: false
      pool:
        #true表示使用连接池；false时，每发送一条数据创建一个连接
        enabled: true
        #连接池最大连接数
        max-connections: 10
        #空闲的连接过期时间，默认为30秒
        idle-timeout: 30000