server:
  servlet:
      # 项目contextPath
      context-path: /rbac

eureka:
  instance:
    hostname: localhsot
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/


spring:
  application:
    name: @artifactId@
    version: @version@
  profiles:
    #active: @package.environment@
    active: dev
    include: datasource,mybatisplus
  activemq:
    broker-url: tcp://localhost:61616
    #true 表示使用内置的MQ，false则连接服务器
    in-memory: false
    pool:
      #true表示使用连接池；false时，每发送一条数据创建一个连接
      enabled: true
      #连接池最大连接数
      max-connections: 10
      #空闲的连接过期时间，默认为30秒
      idle-timeout: 30000
  activiti:
    database-schema-update: true
    process-definition-location-prefix: "classpath*:/bpmn/*.bpmn"
    history-level: full
    db-history-used: true #配置生成history表,默认false,只会生成17张表



cas:
  #cas服务端地址
  server-url-prefix: http://localhost:8180/cas
  #cas服务端登录地址
  server-login-url: http://localhost:8180/cas/login
  #客户端地址
  client-host-url: http://localhost:${server.port}
  #Ticket校验器
  validation-type: CAS

#自定义logoutpath
logout-path: ${cas.server-url-prefix}/logout?service=${cas.server-login-url}

#web starter包含boot starter,boot starter包含logging starter,slf4j的依赖在logging starter中
#官方推荐使用的xml名字的格式为：logback-spring.xml而不是logback.xml，因为带spring后缀的可以使用<springProfile>这个标签。
logging:
  #默认logback-spring.xml ，实际无需配置
  config: classpath:logback-spring.xml
