server:
  servlet:
      # 项目contextPath
      context-path: /rbac

spring:
  application:
    name: @artifactId@
    version: @version@
  profiles:
    active: @package.environment@
    include: datasource,mybatisplus
